name: Hostinger Nighty Deployment
on:
  push:
  workflow_dispatch:

jobs:
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install and build
        run: |
          cd server
          npm install
          npm run build
          mkdir ../deploy
          cp -r ./dist/* ../deploy/
          cp ./package.json ../deploy/

      - name: Copy files to Hostinger
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./deploy/*"
          target: "/home/u113275674/domains/staging-gql.inquesta.org/nodejs/"
          strip_components: 1

