name: Hostinger Nighty Deployment
on:
  push:
  workflow_dispatch:

jobs:
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: node -v
