name: Staging Deployment

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pre-deploy-check:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.master_check.outputs.should_deploy }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'

      - name: Check for latest code & Environments
        id: master_check
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_eddsa
          chmod 600 ~/.ssh/id_eddsa
          
          REMOTE_DATA=$(timeout 30s ssh -o StrictHostKeyChecking=no \
            -o ConnectTimeout=10 \
            -o ServerAliveInterval=15 \
            -p ${{ secrets.SSH_PORT }} \
            -i ~/.ssh/id_eddsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            HASH_FILE="/home/${{ secrets.SSH_USER }}/domains/${{ secrets.API_DOMAIN }}/nodejs/.deploy_hash"
            ENV_FILE="/home/${{ secrets.SSH_USER }}/domains/${{ secrets.API_DOMAIN }}/public_html/.builds/config/.env"
            
            cat $HASH_FILE 2>/dev/null || echo "none"
            echo "---ENDHASH---"
            cat $ENV_FILE 2>/dev/null || echo "none"
          EOF
          ) || { echo "SSH Connection Failed"; exit 1; }

          echo "------- REMOTE DATA START"
          echo "$REMOTE_DATA"
          echo "------- REMOTE DATA END"

          REMOTE_HASH=$(echo "$REMOTE_DATA" | sed -n '1p')
          ENV_CONTENT=$(echo "$REMOTE_DATA" | sed '1,2d')

          if [ "$REMOTE_HASH" == "${{ github.sha }}" ]; then
            echo "No changes detected. Skipping deployment."
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          cd ci
          echo "$ENV_CONTENT" > .env
          echo "------"
          cat .env
          echo "------"
          pip install -r requirements.txt
          
          python checker.py
          
          echo "Environment check passed."
          echo "should_deploy=true" >> $GITHUB_OUTPUT

  deploy-backend-hostinger:
    runs-on: ubuntu-latest
    needs: pre-deploy-check
    if: needs.pre-deploy-check.outputs.should_deploy == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "24"

      - name: Install and build
        run: |
          cd server
          npm install
          npm run build

          mkdir ../deploy
          cp -r ./dist ../deploy/
          cp -r ./src ../deploy/
          cp ./package.json ../deploy/
          cp ./package-lock.json ../deploy/
          echo "${{ github.sha }}" > ../deploy/.deploy_hash

      - name: Clean old folders on Server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf /home/${{ secrets.SSH_USER }}/domains/${{ secrets.API_DOMAIN }}/nodejs/dist
            rm -rf /home/${{ secrets.SSH_USER }}/domains/${{ secrets.API_DOMAIN }}/nodejs/src

      - name: Copy files to Hostinger
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy/*"
          target: "/home/${{ secrets.SSH_USER }}/domains/${{ secrets.API_DOMAIN }}/nodejs/"
          strip_components: 1

      - name: Finalize Deployment on Server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/domains/${{ secrets.API_DOMAIN }}/nodejs

            export PATH="$PATH:/opt/alt/alt-nodejs24/root/bin"
            npm ci --omit=dev

            mkdir -p tmp
            touch tmp/restart.txt

  deploy-frontend-cloudflare:
    runs-on: ubuntu-latest
    needs: pre-deploy-check
    if: needs.pre-deploy-check.outputs.should_deploy == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Install Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "24"

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          VITE_API_URL="https://${{ secrets.API_DOMAIN }}" npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./frontend/dist --project-name=inquesta-staging --branch main
